theme: 
  switch: true 
  default: style-light # style-light style-dark

favicon:
  logo: /img/favicon-32.png
  icon16: /img/favicon-16.png
  icon32: /img/favicon-32.png
  appleTouchIcon: apple-touch-icon.png
  webmanifest: /site.webmanifest
  visibilitychange: true
  hidden: failure.ico
  showText: (/≧▽≦/)咦！又好了！
  hideText: (●—●)喔哟，崩溃啦！

cdn:
  css: 
  js:
    head:
    base: 
    async: 
    defer: 

assets:
  icons: 
    type: font 
    # 这里是您从 iconfont 处获得的图标链接。
    css: //at.alicdn.com/t/font_383361_cfn4m13f4v.css
    js:


user:
  name: 去故事化
  first_name: 事化
  last_name: 去故
  email: 2302643352@qq.com
  domain: https://www.imalun.com
  avatar: /img/avatar.jpg
  describe: 网站简介。
  ruleText: 暂不接受个人博客以外的友链申请，确保您的网站内容积极向上，文章至少30篇，原创70%以上，部署HTTPS。

top_bars:
  - title: home
    url: /
  - title: archives
    url: /archives/
    noswup: true
  - title: links
    url: /links/

sidebar:
  social:  # 社交地址
    - name: github
      icon: fab fa-github   
      url: https://github.com 
    - name: gitee
      icon: iconfont cg-gitee
      url: https://gitee.com
  typedTextPrefix: I`m
  typedText: [ 'Web Developer' ]
  info: # 个人信息 
      - key: 星球 
        val: 火星
      - key: 城市
        val: 格林小镇
      - key: 年龄
        val: 19

banner:
  index:
    type: img
    bgurl: https://pic1.zhimg.com/v2-b3c2c6745b9421a13a3c4706b19223b3_r.jpg?source=1940ef5c
    bannerTitle: 树深时见鹿，<br>溪午不闻钟。
    bannerText: Hi my new friend!

footer:
  copyrightYear: 2020
  powered:
    enable: true
  beian:
    enable: true
    icp: 苏ICP备xxxxxxxx号
  live_time:
    enable: false
    prefix: footer.tips
    start_time: 04/10/2022 17:00:00

reward:
  enable: true
  comment: I'm so cute. Please give me money.
  methods:
    - name: 支付宝
      path: 二维码地址

toc:
  enable: true
  list_number: true
  max_depth: 3
  min_depth: 1

lazyload:
  enable: true
archive:
  type: more # less more

creative_commons:
  license: by-nc-sa
  language: deed.zh
  post: false
  clipboard: false

cover:
  default: /img/block.jpg
  type: img

datetime_foramt:
  post_card:
    date: YY/MM/DD
    time: HH:mm
  post_info:
    date: MM/DD
    time: HH:mm
  archive:
    date: MM/DD
    time: HH:mm

icons:
  # 主题切换图标
  sun: far fa-sun
  moon: far fa-moon
  # 首页视频播放
  play: fas fa-play
  # 邮箱
  email: far fa-envelope
  # 分类进入图标
  next: fas fa-arrow-right
  # 文章详情 日期
  calendar: far fa-calendar-alt
  # 文章详情 时间
  clock: far fa-clock
  # 文章详情 作者
  user: far fa-user
  # 返回顶部 v1.1.3+
  back_top: fas fa-arrow-up
  # 查询 v1.1.5+
  search: fas fa-search
  # 关闭 v1.1.5+
  close: fas fa-times
  # 打赏 v1.1.7+
  reward: fas fa-hand-holding-usd
